[package]
name = "lnx"
version = "0.1.0"
edition = "2021"

[features]
default = [ "socket" ]
socket = []
startup = []

[dependencies]
lnx-syscall = { path = "deps/lnx-syscall" }
lnx-flags = { path = "deps/lnx-flags" }

[workspace]
members = [ "deps/*" ]
