[package]
name = "lnx"
version = "0.1.0"
edition = "2021"

[features]
default = [ "socket" ]
socket = []

[dependencies]
lnx-syscall = { path = "deps/lnx-syscall" }

[workspace]
members = [ "deps/*" ]
